sudo: false
language: python
python:
  - '2.7'

env:
  global:
    - CARAVEL_DATABASE_URL=postgresql://localhost/psi_bi_test

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE psi_bi_test;'

install:
  - pip install -r requirements.txt

script:
  - caravel db upgrade
  - caravel init
  - caravel load_examples
  - caravel runserver -d
