sudo: false
language: python
python:
- '2.7'
env:
  global:
  - CARAVEL_DATABASE_URL=postgresql://localhost/psi_bi_test
services:
- postgresql
before_script:
- psql -U postgres -c 'CREATE DATABASE psi_bi_test;'
install:
- pip install -r requirements.txt
script:
- caravel db upgrade
- caravel init
- caravel load_examples
deploy:
  provider: heroku
  api_key:
    secure: CCl7KwEYVIP4EZC7eB3dpWtZYGWWUJaFY0+vauuor0gYvhnkRhD88jRujqsPxRg2fqPF+ndKd5qEckPtFwQ7mxRoG2ocfeisaKg/LezHyA11pruV+jRxmv/r91MKuvut2Kk5TOPsDj6ARz87tAIFKutCJ4XHoY4NxJLeb1XSctQXjZb4QhJ7wostqr2+KhhUsIHFz12V4xL5x8o/uvZZM0+PBUt/aNqaJxUQmTuFcoAXyuMby/+vHGZUQrCzbYa+/M6qlq1hzsJoomFxM92WrQcoacFzp9lZDKqmU700baibvhI99VQ+A7C6tK25zcMUpAzQYCS+oDvw1OauvCPHfWYnLMKe2Q1vLWc/VroOID7G9aJ1rsb+GF/8c0PnGPKie3Ozta92dQBKEzNnUFGbai+xTmnBV0VWlmdu7UOj9zDm4AnD34qhrX5B7o9LWfkc7RSBUZIhY3zw3JctL941VFJmd3gfI5bv0j9bIItqV/gxOz7ORehaxN54yqgExT3REyxdQDUsCM4pg8Eoj6baYo9qczlt4ExuE6wao1099dnmB5AOu2rNe8OWqPQQArY09Ry/QpiRRLi8HX+8CVmVJQiEMNymZQFDftqXcZ3Es7iKO1j6J5DmZC0F4pAbmxNycvzVCensw9ngsLohv4/vagpGiA5+R/OgfPxTLakqJWc=
  app: psi-bi
  on:
    repo: betterlife/psi-bi
    all_branches: true
